// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: internal/proto/mail_box.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *MailBox) Reset() {
	*x = MailBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailBox) ProtoMessage() {}

func (x *MailBox) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailBox.ProtoReflect.Descriptor instead.
func (*MailBox) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{0}
}

func (x *MailBox) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MailBox) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mailbox *MailBox `protobuf:"bytes,1,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
}

func (x *CreateMailRequest) Reset() {
	*x = CreateMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailRequest) ProtoMessage() {}

func (x *CreateMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailRequest.ProtoReflect.Descriptor instead.
func (*CreateMailRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMailRequest) GetMailbox() *MailBox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

type CreateMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mailbox *MailBox `protobuf:"bytes,1,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
}

func (x *CreateMailResponse) Reset() {
	*x = CreateMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailResponse) ProtoMessage() {}

func (x *CreateMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailResponse.ProtoReflect.Descriptor instead.
func (*CreateMailResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMailResponse) GetMailbox() *MailBox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

type ReadMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ReadMailRequest) Reset() {
	*x = ReadMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailRequest) ProtoMessage() {}

func (x *ReadMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailRequest.ProtoReflect.Descriptor instead.
func (*ReadMailRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ReadMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mailbox *MailBox `protobuf:"bytes,1,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
}

func (x *ReadMailResponse) Reset() {
	*x = ReadMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailResponse) ProtoMessage() {}

func (x *ReadMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailResponse.ProtoReflect.Descriptor instead.
func (*ReadMailResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMailResponse) GetMailbox() *MailBox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

type DeleteMailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *DeleteMailRequest) Reset() {
	*x = DeleteMailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMailRequest) ProtoMessage() {}

func (x *DeleteMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMailRequest.ProtoReflect.Descriptor instead.
func (*DeleteMailRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteMailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteMailResponse) Reset() {
	*x = DeleteMailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_mail_box_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMailResponse) ProtoMessage() {}

func (x *DeleteMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_mail_box_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMailResponse.ProtoReflect.Descriptor instead.
func (*DeleteMailResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_mail_box_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_proto_mail_box_proto protoreflect.FileDescriptor

var file_internal_proto_mail_box_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x07, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3d, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x42, 0x6f, 0x78, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x22, 0x3e, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x42, 0x6f, 0x78, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x22, 0x27, 0x0a, 0x0f,
	0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3c, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x61, 0x69,
	0x6c, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x6f, 0x78, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x22, 0x29, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2e,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xd5,
	0x01, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x43, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_mail_box_proto_rawDescOnce sync.Once
	file_internal_proto_mail_box_proto_rawDescData = file_internal_proto_mail_box_proto_rawDesc
)

func file_internal_proto_mail_box_proto_rawDescGZIP() []byte {
	file_internal_proto_mail_box_proto_rawDescOnce.Do(func() {
		file_internal_proto_mail_box_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_mail_box_proto_rawDescData)
	})
	return file_internal_proto_mail_box_proto_rawDescData
}

var file_internal_proto_mail_box_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_proto_mail_box_proto_goTypes = []interface{}{
	(*MailBox)(nil),            // 0: proto.MailBox
	(*CreateMailRequest)(nil),  // 1: proto.CreateMailRequest
	(*CreateMailResponse)(nil), // 2: proto.CreateMailResponse
	(*ReadMailRequest)(nil),    // 3: proto.ReadMailRequest
	(*ReadMailResponse)(nil),   // 4: proto.ReadMailResponse
	(*DeleteMailRequest)(nil),  // 5: proto.DeleteMailRequest
	(*DeleteMailResponse)(nil), // 6: proto.DeleteMailResponse
}
var file_internal_proto_mail_box_proto_depIdxs = []int32{
	0, // 0: proto.CreateMailRequest.mailbox:type_name -> proto.MailBox
	0, // 1: proto.CreateMailResponse.mailbox:type_name -> proto.MailBox
	0, // 2: proto.ReadMailResponse.mailbox:type_name -> proto.MailBox
	1, // 3: proto.BookService.CreateMail:input_type -> proto.CreateMailRequest
	3, // 4: proto.BookService.GetMail:input_type -> proto.ReadMailRequest
	5, // 5: proto.BookService.DeleteMail:input_type -> proto.DeleteMailRequest
	2, // 6: proto.BookService.CreateMail:output_type -> proto.CreateMailResponse
	4, // 7: proto.BookService.GetMail:output_type -> proto.ReadMailResponse
	6, // 8: proto.BookService.DeleteMail:output_type -> proto.DeleteMailResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_mail_box_proto_init() }
func file_internal_proto_mail_box_proto_init() {
	if File_internal_proto_mail_box_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_mail_box_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_mail_box_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_mail_box_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_mail_box_proto_goTypes,
		DependencyIndexes: file_internal_proto_mail_box_proto_depIdxs,
		MessageInfos:      file_internal_proto_mail_box_proto_msgTypes,
	}.Build()
	File_internal_proto_mail_box_proto = out.File
	file_internal_proto_mail_box_proto_rawDesc = nil
	file_internal_proto_mail_box_proto_goTypes = nil
	file_internal_proto_mail_box_proto_depIdxs = nil
}
